# Generated by Django 5.0 on 2023-12-10 22:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="activate",
            new_name="active",
        ),
    ]
