# Generated by Django 5.0 on 2023-12-10 22:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0002_rename_activate_category_active"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="categories",
            new_name="category",
        ),
    ]
